### ISSUE TITLE
UDPSocket#recvfrom nil return crashes BufferedTokenizer

### ISSUE THREAD

**Issue by colinsurprenant** [logstash-plugins/logstash-input-udp#4]
as described in elastic/logstash#3385 `UDPSocket#recvfrom` can return a `nil` payload and pass it on to the line codec which uses `BufferedTokenizer` and eventually crash on calling the `join` method on an array with a `nil` value. 

We should definitely discard `nil` payload returns in https://github.com/logstash-plugins/logstash-input-udp/blob/fae6a4fa88dcf0a071ddef484f0221b58a0bedce/lib/logstash/inputs/udp.rb#L79-L80

Not sure if we should also add a safety net in `BufferedTokenizer` for `nil` data? will open a separate issue.

**Comment by colinsurprenant** [comment]
there is actually something else going on because `BufferedTokenizer` does not accept `nil` payload but it does end up with a `nil` object in its `@input` array... investigating

**Comment by xubo-fei** [comment]
Hi,

Is there any progress on this?

I am seeing very similar issue in logstash-input-udp-3.1.0

{"exception"=>#<TypeError: can't convert nil into String>, "backtrace"=>["org/jruby/RubyArray.java:1892:in `join'", "org/jruby/RubyArray.java:1898:in `join'", "/opt/logstash/logstash-core/lib/logstash/util/buftok.rb:87:in `extract'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-line-3.0.2/lib/logstash/codecs/line.rb:39:in `decode'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-udp-3.1.0/lib/logstash/inputs/udp.rb:118:in `inputworker'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-udp-3.1.0/lib/logstash/inputs/udp.rb:89:in `udp_listener'"]}

We also see messages mangled.

also posted thread on 

https://discuss.elastic.co/t/udp-input-plugin-error-typeerror-cant-convert-nil-into-string/110565/2

**Comment by colinsurprenant** [comment]
Thanks for the headsup @xubo-fei .

**Comment by colinsurprenant** [comment]
I can actually reproduce using this:

```
$ bin/logstash -e 'input { udp { codec => line  workers => 2 port => 5015  } } output { stdout { codec => dots } }'
```
```
yes "foobar" | nc -u localhost 5015
```

After some investigations the probable cause of the problem here is that the line codec (and codecs in general) is not thread safe, in particular the `FileWatch::BufferedTokenizer` class in the codec which becomes an unprotected shared resource across the udp input threads which explains the nil values and the messages mangling as described in the discuss thread mentioned. 

I am looking at the best solution for this.

**Comment by colinsurprenant** [comment]
until we push a fix, a temporary workaround is to use a single udp input worker (by default it is set to 2)

```
udp {
  port => XX
  codec => line
  workers => 1
}
```

**Comment by xubo-fei** [comment]
Thank you very much! Please also keep us updated.

**Comment by colinsurprenant** [comment]
created logstash-plugins/logstash-codec-line/pull/13 to fix the concurrency issue with the line codec.
